name: CI Pipeline

on:
  push:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: v1-dependencies-${{ hashFiles('package.json', 'package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Save dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' && github.event.action == 'created') || (github.ref == 'refs/heads/bugfix/ci' && github.event_name == 'push')
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist/

      - name: Authenticate with npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish --access=public